  tags:
    - CI
    - ace
  steps:
  - id: github_known_hosts
    name: gcr.io/cloud-builders/gcloud
    entrypoint: /bin/bash
    args:
    - '-c'
    - 'gcloud secrets versions access latest --secret=github-known-hosts > /root/.ssh/known_hosts && chmod 600 /root/.ssh/known_hosts'
    volumes:
    - name: 'ssh-setup'
      path: /root/.ssh
  - id: deploy_key
    name: gcr.io/cloud-builders/gcloud
    entrypoint: /bin/bash
    args:
    - '-c'
    - 'gcloud secrets versions access latest --secret=${_DEPLOY_KEY} > /root/.ssh/id_rsa && chmod 600 /root/.ssh/id_rsa'
    volumes:
    - name: 'ssh-setup'
      path: /root/.ssh
  - id: checkout_from_github
    name: gcr.io/cloud-builders/git
    args:
    - 'clone'
    - 'git@github.com:overleaf/ace-builds.git'
    - '/workspace/build'
    volumes:
    - name: 'ssh-setup'
      path: /root/.ssh
  - id: install
    name: node:12
    args:
    - 'npm'
    - 'ci'
  - id: build
    name: node:12
    args:
    - 'make'
    - 'minimal'
    - '-j2'
    env:
    - SHA=$COMMIT_SHA
  - id: release
    name: node:12
    dir: '/workspace'
    args:
    - 'make'
    - 'release'
    env:
    - SHA=$COMMIT_SHA
    - GIT_COMMITTER_NAME=$_GIT_USERNAME
    - GIT_COMMITTER_EMAIL=$_GIT_EMAIL
    - GIT_AUTHOR_NAME=$_GIT_USERNAME
    - GIT_AUTHOR_EMAIL=$_GIT_EMAIL
    volumes:
    - name: 'ssh-setup'
      path: /root/.ssh
  - id: package_url
    name: node:12
    dir: '/workspace'
    args:
    - 'make'
    - 'package_url'
    env:
    - SHA=$COMMIT_SHA
  substitutions:
    _GIT_EMAIL: developers@overleaf.com
    _GIT_USERNAME: OverleafDevelopers
    _DEPLOY_KEY: ace-builds-deploy-key
  images: []

